// IKAN KEMBUNG

var dataKembung1 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Ikan kembung atau seringkali disebut indian mackerel (Rastrelliger kanagurta) ikan kembung laki-laki dan (Rastrelliger brachysoma) ikan kembung perempuan termasuk ikan pelagis kecil yang memiliki nilai ekonomis menengah, sehingga terhitung sebagai komoditas yang cukup penting bagi perikanan tangkap. Ikan kembung memiliki panjang maksimal 35 cm TL. Termasuk ikan pelagis di zona neritik, oseanodrom. Swimming layer berkisar antara 20 – 90 m. Penyebaran terbanyak di Samudera Hindia dan sebagian Pasifik Timur (Larasati, 2011).</p>';

var dataKembung2 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Ikan ini merupakan jenis schooling fish atau ikan yang bergerombol. Ikan ini berenang dengan cara mulut dan tapis insang terbuka. Ini merupakan cara ikan ini makan dengan menyaring plankton yang masuk ke mulut dan tersaring di tapis insang. Panjang tubuh  maksimal ikan kembung bias mencapai 35 cm.</p>';

var dataKembung3 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Di Indonesia sendiri penyebarannya sangat luas, diantaranya selat malaka (Dekat Banda Aceh), Laut Jawa, Laut Selatan Jawa, dan perairan timur laut lainnya. Ikan kembung juga banyak di temuan di perairan lain di luar Indonesia.</p>';
var dataKembung4 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2"> Ikan kembung perempuan (Rastrelliger brachysoma) memiliki genus yang sama dengan ikan kembung lelaki (Rastrelliger kanagurta). Ciri yang membedakannya adalah adanya satu bintik atau totol hitam dekat sirip dada pada ikan kembung lelaki. Selain itu, ikan kembung perempuan memiliki perut yang lebih lebar dibandingkan ikan kembung lelaki.</p>';
var dataKembung5 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Jenis ikan Kembung yang tertangkap di Indonesia terdiri dari spesies: Rastelliger brachysoma, R. faughni dan R. kanagurta. Nama lokal: Rumahan, Temenong, Mabong, Pelaling, Banyar, Kembung Lelaki.</p>';

var tableKembung =
    '<table style="border-color:#aaa;border-collapse: collapse;background:#fafafa;text-align:center" border="1"> <thead style="background:#0076BE;color:white;font-weight:semibold"> <tr> <th style="padding:12px 0;border-color:white">Kingdom</th> <th style="padding:12px 0;border-color:white">Animalia</th> </tr> </thead> <tbody style="text-align:center"> <tr> <td style="padding:12px 0;border-color:#aaa">Filum</td> <td style="padding:12px 0;border-color:#aaa">Chordata</td> </tr> <tr> <td style="padding:12px 0;border-color:#aaa">Kelas</td> <td style="padding:12px 0;border-color:#aaa">Pisces</td> </tr> <tr> <td style="padding:12px 0;border-color:#aaa">SubKelas</td> <td style="padding:12px 0;border-color:#aaa">Teleostei</td> </tr> <tr> <td style="padding:12px 0;border-color:#aaa">Ordo</td> <td style="padding:12px 0;border-color:#aaa">Percomorpy</td> </tr> <tr> <td style="padding:12px 0;border-color:#aaa">Sub Ordo</td> <td style="padding:12px 0;border-color:#aaa">Scombridae</td> </tr> <tr> <td style="padding:12px 0;border-color:#aaa">Famili</td> <td style="padding:12px 0;border-color:#aaa">Scombridae</td> </tr> <tr> <td style="padding:12px 0;border-color:#aaa">Genus</td> <td style="padding:12px 0;border-color:#aaa">Rastrelliger</td> </tr> <tr> <td style="padding:12px 0;border-color:#aaa">Spesies laki-laki</td> <td style="padding:12px 0;border-color:#aaa">Rastrelliger kanagurta</td> </tr> <tr> <td style="padding:12px 0;border-color:#aaa">Spesies perempuan</td> <td style="padding:12px 0;border-color:#aaa">Rastrelliger brachysoma</td> </tr> <tr> <td style="padding:12px 0;border-color:#aaa">Nama Umum</td> <td style="padding:12px 0;border-color:#aaa">Indian mackerel (Inggris), kembung (Indonesia)</td> </tr> </tbody> </table>';

var morfologi1 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Ikan kembung lelaki memiliki ciri-ciri terdapat dua sirip punggung secara terpisah yang masing-masing terdiri dari 8 hingga 9 jari-jari lemah. Sirip dada terdiri dari 16 hingga 19 jari-jari sirip lemah, sirip perut terdiri dari 7 hingga 8 jari-jari lemah, sirip ekor terdiri dari 50 hingga 52 jari-jari lemah bercabang dan sisik pada garis rusuk (linea lateralis) terdiri dari 127 hingga 130 buah sisik. Selain itu, ikan ini memiliki panjang total 3,4 sampai 3,8 kali tinggi badan dan panjang kepala lebih dari tinggi kepala (Saanin, 1968). Ditambahkan oleh Wiadnya ( 2012), di belakang sirip punggung kedua dan sirip dubur terdapat 5 sirip tambahan (finlet) dan terdapat sepasang keel pada ekor. Pada ikan Kembung Lelaki terdapat noda hitam di belakang sirip dada. Pada semua jenis terdapat barisan noda hitam di bawah sirip punggung. Punggung berwarna biru kehijauan, sedangkan bagian perut berwarna kuning keperakan.</p>';

var morfologi2 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Ikan kembung perempuan memiliki bentuk tubuh pipih dengan bagian dada lebih besar daripada bagian tubuh yang lain dan ditutupi oleh sisik yang berukuran kecil dan tidak mudah lepas. Warna tubuh biru kehijauan di bagian punggung dengan titik gelap atau totol-totol hitam di atas garis rusuk sedangkan bagian bawah tubuh berwarna putih perak. Sirip punggung (dorsal) terpisah nyata menjadi dua buah sirip, masing-masing terdiri atas 10 hingga 11 jari-jari keras dan 12 hingga 13 jari-jari lemah ( Direktorat Jendral Perikanan, 1979). Sirip dubur (anal) berjari-jari lemah 12. Di belakang sirip punggung kedua dan sirip dubur terdapat 5 sampai 6 sirip tambahan yang disebut finlet. Sirip perut (ventral) terdiri dari 1 jari-jari keras dan 5 jari-jari lemah. Sirip ekor (caudal) bercagak dalam dan sirip dada (pectoral) lebar dan meruncing (Anwar 1970 in Ruswahyuni 1979). Mata mempunyai selaput yang berlemak, gigi yang kecil pada tulang rahang. Tapis insang halus 29-34, pada bagian bawah busur insang pertama tapis insang panjang dan banyak terlihat seolah-olah bulu jika mulutnya dibuka (Burhanudin et al 1984 in Astuti 2007).</p>';
var reproduksi1 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2"> Nikolsky (1963) in Larasati (2011), menyatakan bahwa ada tiga alasan utama yang menyebabkan beberapa spesies ikan melakukan migrasi, antara lain usaha untuk mencari daerah yang banyak makanannya (feeding), usaha untuk mencari daerah tempat berpijah (spawning), dan adanya perubahan beberapa faktor lingkungan seperti temperatur, salinitas, dan suhu.</p>';
var reproduksi2 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Fischer dan Whitehead (1974) in Zen (2006) menyatakan bahwa ikan kembung perempuan (Rastrelliger brachysoma) hidup berkelompok dalam jumlah yang besar pada perairan pantai dengan kedalaman antara 10-50 meter. Ikan ini melakukan ruaya pemijahan yang bersifat oceanodromus yaitu ikan menghabiskan siklus hidupnya di daerah pantai dan memijah di daerah laut lepas. Chirastit (1962) in Larasati (2011) menduga bahwa Ikan kembung perempuan yang sudah matang gonad beruaya dari daerah pantai ke laut lepas sedangkan ikan juvenil beruaya dari laut lepas ke daerah pantai untuk membesar.</p>';
var reproduksi3 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Menurut penelitian Pathansali (1961) in Larasati (2011) di Glugor, Penang, Malaysia, ikan kembung lelaki (Rastrelliger kanagurta) memijah dua kali selama musim pemijahan, begitu juga menurut penelitian Boonprakop (1965) in Larasati (2011) di Teluk Thailand yang menyatakan bahwa ikan kembung (Rastrelliger spp.) memijah lebih dari satu kali selama musim pemijahan. Pemijahan yang terjadi pada ikan kembung yaitu sekumpulan telur dilepaskan terlebih dahulu, berikutnya sekumpulan telur akan dilepaskan kembali dengan interval yang pendek. Ikan kembung memiliki sebaran diameter telur yang luas. Kelompok ukuran diameter telur yang besar merupakan perkembangan dari kelompok ukuran diameter telur sebelumnya dan mungkin merupakan sekumpulan telur yang terakhir dilepaskan setelah pemijahan pertama selama musim pemijahan.</p>';
var reproduksi4 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2"> Ikan kembung lelaki (Rastrelliger kanagurta) di Laut Jawa mempunyai dua musim pemijahan yang berlangsung pada musim barat mulai dari bulan Oktober hingga Februari dan pada musim timur yaitu mulai dari bulan Juni hingga September (Astuti 2007), sedangkan ikan kembung perempuan (Rastrelliger brachysoma) memiliki musim pemijahan dari bulan Maret sampai dengan bulan Oktober (Ochavillo et al. 1991; Froese and Pauly 2006 in Lachita 2006).</p>';
var habitat1 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Ikan kembung merupakan kelompok ikan epipelagis dan neritik di daerah pantai dan laut. Penyebaran ikan kembung dapat dibagi menjadi dua bagian, yaitu penyebaran secara vertikal dan horisontal. Penyebaran secara vertikal dipengaruhi oleh suhu dan gerakan harian plankton sedangkan penyebaran secara horizontal dipengaruhi oleh arus laut. Penyebaran ikan ini meliputi Samudra Pasifik, Laut Andaman, Thailand, Filipina, Papua New Guinea, Pulau Solomon, dan Fiji. Daerah 6 penyebaran di perairan pantai Indonesia dengan konsentrasi terbesar di Kalimantan, Sumatra Barat, Laut Jawa, Selat Malaka, Muna-Buton, arafuru, TL Siam (Direktorat Jendral Perikanan 1979).</p>';
var habitat2 =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Ikan Kembung tersebar membentuk gerombolan (schooling) besar di wilayah Perairan Pantai. Ikan ini sering ditemukan bersama dengan ikan famili Clupeidae seperti Lemuru dan Tembang. Jenis makanannya adalah Phytoplankton (Diatom), Zooplankton (Cladocera, Ostracoda, Larva Polychaeta). Ikan dewasa memakan Makroplankton seperti larva Udang dan ikan (Wiadnya, 2012).</p>';
var tingkahlaku =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Ikan kembung termasuk ikan pemakan plankton. Kebiasaan makanan ikan kembung yaitu memangsa plankton, copepod, atau crustacea (Kriswantoro dan Sunyoto 1986 in Sari 2004). Plankton tersebut disaring dengan tapis insang. Tapis 7 insang pada ikan kembung lelaki lebih besar karena plankton yang dimakannya memilki ukuran yang lebih besar, sedangkan pada kembung perempuan (R. brachysoma) memiliki tapis insang yang halus karena plankton yang dimakannya berukuran kecil (Nontji 2005 in Astuti 2007). Larva kembung memakan fitoplakton seperti jenis diatom laut dan jenis zooplankton kecil seperti ladoceran, ostracods, larva polychaetes, dan lain-lain.</p>';
var peranikankembungdiperairan =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Dalam perairan ikan kembung berperan sebagai konsumen tingkat 1, dimana ikan kembung memangsa plankton, copepod, atau crustacea.</p>';
var manfaatikankembung =
    '<p style="text-align:justify;color:#333333;text-indent:50px;line-height:1.2">Sejak awal tahun 1976, ikan Kembung tertangkap terutama dengan alat Purse Seine. Sebelum itu dia lebih banyak ditangkap dengan alat Payang dan Bagan. Ikan ini bisa mencapai panjang 35 cm, sering tertangkap pada ukuran sekitar 25 cm. hasil tangkapan biasanya dijual segar dan dalam bentuk Pindang Banyar dan ikan asin yang lebih tahan lama. Ikan kembung yang masih kecil juga sering digunakan sebagai umpan hidup untuk memancing cakalang. (Wiadnya, 2012).</p>';
var penulis =
    '<p style="font-weight:600;font-size:17px">Eka Rahmawati</p><p>FPIK Universitas Brawijaya Angkatan 2012</p>';
